let joyas=JSON.parse(localStorage.getItem('joyasERP'))||[{referencia:'MD-AN-1001',nombre:'Anillo Aurora Oro 18K',categoria:'Anillo',material:'Oro 18K',precio:1250000,stock:2,proveedor:'Gemas Andinas SAS',certificado:true,estado:'Disponible'},{referencia:'MD-CD-1002',nombre:'Cadena Toscana Plata 925',categoria:'Cadena',material:'Plata 925',precio:420000,stock:5,proveedor:'Brillo Capital',certificado:true,estado:'Disponible'},{referencia:'MD-RJ-1003',nombre:'Reloj Elite Acero Premium',categoria:'Reloj',material:'Acero premium',precio:980000,stock:1,proveedor:'Luxury Time CO',certificado:false,estado:'Reservada'}];
function mostrarAnimaciones(){document.querySelectorAll('.animar').forEach(function(elemento){if(elemento.getBoundingClientRect().top<window.innerHeight-80){elemento.classList.add('visible')}})}
window.addEventListener('load',mostrarAnimaciones);window.addEventListener('scroll',mostrarAnimaciones);mostrarAnimaciones();
function formatoCOP(valor){return '$'+Number(valor).toLocaleString('es-CO')}
function renderizarJoyas(){const tabla=document.getElementById('tabla-joyas');const totalProductos=document.getElementById('total-productos');const valorInventario=document.getElementById('valor-inventario');const stockTotal=document.getElementById('stock-total');const progreso=document.getElementById('progreso-stock');if(!tabla)return;tabla.innerHTML='';let sumaValor=0;let sumaStock=0;joyas.forEach(function(joya){sumaValor+=Number(joya.precio)*Number(joya.stock);sumaStock+=Number(joya.stock);let clase='disponible';if(joya.estado==='Reservada')clase='reservada';if(joya.estado==='Vendida')clase='vendida';const fila=document.createElement('tr');fila.innerHTML=`<td>${joya.referencia}</td><td>${joya.nombre}</td><td><span class="tag ${clase}">${joya.estado}</span></td>`;tabla.appendChild(fila)});totalProductos.textContent=joyas.length;valorInventario.textContent=formatoCOP(sumaValor);stockTotal.textContent=sumaStock;progreso.style.width=Math.min((sumaStock/50)*100,100)+'%'}
renderizarJoyas();
const formJoya=document.getElementById('form-joya');if(formJoya){formJoya.addEventListener('submit',function(e){e.preventDefault();const referencia=document.getElementById('referencia').value.trim();const nombre=document.getElementById('nombre').value.trim();const categoria=document.getElementById('categoria').value;const material=document.getElementById('material').value;const precio=Number(document.getElementById('precio').value);const stock=Number(document.getElementById('stock').value);const proveedor=document.getElementById('proveedor').value.trim();const certificado=document.getElementById('certificado').checked;if(referencia===''||nombre===''||categoria===''||material===''||precio<=0||stock<=0||proveedor===''){alert('Por favor completa todos los campos obligatorios del ERP.');return}const existe=joyas.some(function(item){return item.referencia.toLowerCase()===referencia.toLowerCase()});if(existe){alert('Ya existe una joya con esa referencia.');return}const nuevaJoya={referencia,nombre,categoria,material,precio,stock,proveedor,certificado,estado:'Disponible'};joyas.push(nuevaJoya);localStorage.setItem('joyasERP',JSON.stringify(joyas));document.getElementById('mensaje-guardado').textContent='Joya guardada correctamente en el ERP: '+referencia;formJoya.reset();renderizarJoyas()})}
const btnBuscar=document.getElementById('btn-buscar');if(btnBuscar){btnBuscar.addEventListener('click',function(){const valor=document.getElementById('buscar-referencia').value.trim().toLowerCase();const resultado=document.getElementById('resultado-busqueda');const joya=joyas.find(function(item){return item.referencia.toLowerCase()===valor});if(!joya){resultado.innerHTML='No se encontro ninguna joya con esa referencia.';return}resultado.innerHTML=`<strong>Referencia:</strong> ${joya.referencia}<br><strong>Nombre:</strong> ${joya.nombre}<br><strong>Categoría:</strong> ${joya.categoria}<br><strong>Material:</strong> ${joya.material}<br><strong>Precio:</strong> ${formatoCOP(joya.precio)}<br><strong>Stock:</strong> ${joya.stock}<br><strong>Proveedor:</strong> ${joya.proveedor}<br><strong>Certificado:</strong> ${joya.certificado?'Si':'No'}<br><strong>Estado:</strong> ${joya.estado}`})}
const canvas=document.getElementById('canvas-flujo');if(canvas){const ctx=canvas.getContext('2d');let dibujando=false;canvas.addEventListener('mousedown',function(){dibujando=true});canvas.addEventListener('mouseup',function(){dibujando=false;ctx.beginPath()});canvas.addEventListener('mouseleave',function(){dibujando=false;ctx.beginPath()});canvas.addEventListener('mousemove',function(e){if(!dibujando)return;const rect=canvas.getBoundingClientRect();const x=(e.clientX-rect.left)*(canvas.width/rect.width);const y=(e.clientY-rect.top)*(canvas.height/rect.height);ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#8a641d';ctx.lineTo(x,y);ctx.stroke();ctx.beginPath();ctx.moveTo(x,y)});document.getElementById('limpiar-canvas').addEventListener('click',function(){ctx.clearRect(0,0,canvas.width,canvas.height)})}
const notas=document.getElementById('notas-equipo');const guardarNotas=document.getElementById('guardar-notas');if(notas){const notasGuardadas=localStorage.getItem('notasEquipoJoyeria');if(notasGuardadas){notas.innerText=notasGuardadas}}if(guardarNotas){guardarNotas.addEventListener('click',function(){localStorage.setItem('notasEquipoJoyeria',notas.innerText);alert('Notas del equipo guardadas correctamente.')})}
